name: running test, build image, push registry, deploy

on:
  push:
    branches: [main]

jobs:
  running_test:
    name: Running Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - name: Run Tests
        run: go test -v ./... -cover

  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    needs: running_test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t faqihazh/alta:latest .
      - name: Log in to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image
        run: docker push faqihazh/alta:latest

  deploy_ec2:
    name: Deploy EC2
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pastikan Docker diinstal di instance EC2
            which docker || echo "Docker is not installed or not found in PATH."

            # Jalankan perintah
            cd /home || echo "Directory not found."
            docker-compose down || echo "Failed to stop previous containers."
            docker pull faqihazh/alta:latest || echo "Failed to pull latest image."
            docker run -d -p 1323:1323 faqihazh/alta:latest || echo "Failed to run container."
            docker-compose up -d || echo "Failed to start containers."
